 
SELECT 'SALEN' TIPO, A.CODOPERACION , A.CODUNICOCLI, B.APEPATERNO  /*,A.MTOACTMONSOL  ,A.MTORENDDEVGDO*/ , A.MTOEXPORIGINAL  /*,A.MTOEXPNETA*/  ,A.MTOAPREXP, A.MTOTOTALAPR
FROM BDS.FRG_BASE_EXPOSICIONES A
LEFT JOIN BDS.BDR_MAECLIENTE B ON A.CODMES = B.CODMES AND A.CODUNICOCLI = B.CODUNICOCLI
WHERE A.CODMES = &PERIODO_ANT
AND A.TIPCREDITO = '&CATEG'
AND A.CODUNICOCLI||A.CODOPERACION NOT IN (SELECT CODUNICOCLI||CODOPERACION FROM BDS.FRG_BASE_EXPOSICIONES
                                      WHERE CODMES = &PERIODO
                                      AND TIPCREDITO = '&CATEG');
                                      
                                      
SELECT 'INGRESAN' TIPO, A.CODOPERACION , A.CODUNICOCLI, B.APEPATERNO  /*,A.MTOACTMONSOL  ,A.MTORENDDEVGDO*/ , A.MTOEXPORIGINAL  /*,A.MTOEXPNETA*/  ,A.MTOAPREXP, A.MTOTOTALAPR
FROM BDS.FRG_BASE_EXPOSICIONES A
LEFT JOIN BDS.BDR_MAECLIENTE B ON A.CODMES = B.CODMES AND A.CODUNICOCLI = B.CODUNICOCLI
WHERE A.CODMES = &PERIODO
AND A.TIPCREDITO = '&CATEG'
AND A.CODUNICOCLI||A.CODOPERACION NOT IN (SELECT CODUNICOCLI||CODOPERACION FROM BDS.FRG_BASE_EXPOSICIONES
                                      WHERE CODMES = &PERIODO_ANT
                                      AND TIPCREDITO = '&CATEG');
                                      
                                      
SELECT 'MANTIENEN' TIPO, A.CODOPERACION , A.CODUNICOCLI, B.APEPATERNO  /*,A.MTOACTMONSOL  ,A.MTORENDDEVGDO*/ , A.MTOEXPORIGINAL  /*,A.MTOEXPNETA*/  ,A.MTOAPREXP, A.MTOTOTALAPR
FROM BDS.FRG_BASE_EXPOSICIONES A
LEFT JOIN BDS.BDR_MAECLIENTE B ON A.CODMES = B.CODMES AND A.CODUNICOCLI = B.CODUNICOCLI
WHERE A.CODMES = &PERIODO_ANT
AND A.TIPCREDITO = '&CATEG'
AND A.CODUNICOCLI||A.CODOPERACION IN (SELECT CODUNICOCLI||CODOPERACION FROM BDS.FRG_BASE_EXPOSICIONES
                                  WHERE CODMES = &PERIODO
                                  AND TIPCREDITO = '&CATEG');
                                  
                                  
                                  
SELECT 'MANTIENEN' TIPO, A.CODOPERACION , A.CODUNICOCLI, B.APEPATERNO  /*,A.MTOACTMONSOL  ,A.MTORENDDEVGDO*/ , A.MTOEXPORIGINAL  /*,A.MTOEXPNETA*/  ,A.MTOAPREXP, A.MTOTOTALAPR
FROM BDS.FRG_BASE_EXPOSICIONES A
LEFT JOIN BDS.BDR_MAECLIENTE B ON A.CODMES = B.CODMES AND A.CODUNICOCLI = B.CODUNICOCLI
WHERE A.CODMES = &PERIODO
AND A.TIPCREDITO = '&CATEG'
AND A.CODUNICOCLI||A.CODOPERACION IN (SELECT CODUNICOCLI||CODOPERACION FROM BDS.FRG_BASE_EXPOSICIONES
                                  WHERE CODMES = &PERIODO_ANT
                                  AND TIPCREDITO = '&CATEG');

--DETALLE movimiento garante

SELECT a.codmes ,
                     A.VALCATEGARANTE                          AS CODCATEGORIA,
                     A.PCTPONDGARANTE*100                      AS VALPONDERADOR,
                     A.FLGEXPATRASOMAYOR90D                    AS CON_ATRASO,
                     DECODE(NVL(A.VALNIVELRIESGO,0),0,'S','N') AS SIN_CLASIF,
                     0                                         AS EXPOSICION_ORIGINAL,   -- COL I
                     0                                         AS PROV_INGDIF_DET,       -- COL II
                     0                                         AS DERYCONTR,             -- COL III
                     0                                         AS EXPOSICION_NETA,       -- COL IV
                     0                                         AS PRE_SUSTITUCION,       -- COL V
                     A.MTOTOTENTRADAS                          AS POST_SUSTITUCION,      -- COL VI
                     0                                         AS AJUSTE_RCC,            -- COL VII
                     0                                         AS AJUSTE_VOLATILIDAD,    -- COL VIII
                     0                                         AS PRE_GARANTIA,          -- COL IX
                     0                                         AS VAL_GAR_REAL_ELE,      -- COL X
                     0                                         AS MTO_HFX,               -- COL XI
                     0                                         AS MTO_HC,                -- COL XII
                     A.MTOTOTALEXPAJUS                         AS MTO_EXPOSICION_AJU,    -- COL XIII
                     0                                         AS MTO_EXPOSICION_AJU_0,  -- COL XIV
                     0                                         AS MTO_EXPOSICION_AJU_20, -- COL XIV
                     0                                         AS MTO_EXPOSICION_AJU_50, -- COL XIV
                     0                                         AS MTO_EXPOSICION_AJU_100,-- COL XIV
                     A.MTOEXPFINAL                             AS MTO_EXPO_FIN_CAL,      -- COL XV
                     A.MTOTOTALAPR                             AS MTO_ACPR,              -- COL XVI
                     A.MTOTOTALREQCAPITAL                      AS MTO_REQ_PATR           -- COL XVII
              FROM BDS.FRG_REL_GRNTIA_EXPOS A--,
              WHERE A.CODMES         in (&PERIODO_ACT, &PERIODO_ANT)
                AND A.MTOTOTENTRADAS > 0


--///////////////////////////
---------CATEGORIZADOR
--///////////////////////////

--CONSULTA CATEGORIAS DIFERENTES EN DEUDA CORTE CATEGORIZADOR
SELECT C.CODUNICOCLI, E1.CODOPERACION, E2.TIPCREDITO TIPCREDITO_MAR, E1.TIPCREDITO TIPCREDITO_ABR, E2.MTOACTMONSOL SALDO_MAR, E1.MTOACTMONSOL SALDO_ABR
FROM BDS.FRG_BASE_EXPOSICIONES E1,
BDS.FRG_BASE_EXPOSICIONES E2,
DWDE.DWDET_DE_RCC_CLIENTE_BANCA C
WHERE E1.CODMES = &PERIODO_ACTUAL --201606
AND E2.CODMES = &PERIODO_ANTERIOR --201605
AND C.CODMES  = &PERIODO_ACTUAL --201606
AND C.CODBANCA IN ( 2,3)
AND E1.CODOPERACION = E2.CODOPERACION
AND E1.CODUNICOCLI = E2.CODUNICOCLI
AND E1.CODUNICOCLI = C.CODUNICOCLI
--AND E1.TIPCREDITO = '07'
AND E1.TIPCREDITO <> E2.TIPCREDITO;
    


--CONSULTA CATEGORIAS DIFERENTES EN DEUDA CORTE  CATEGORIZADOR
SELECT C.CODIGOUNICO, C2.APEPATERNO, E2.TIPCREDITO TIPCREDITO_01, E1.TIPCREDITO TIPCREDITO_02, sum(E2.MTOACTMONSOL) SALDO_01, sum(E1.MTOACTMONSOL) SALDO_02
FROM BDS.FRG_BASE_EXPOSICIONES E1
LEFT JOIN BDS.BDR_MAECLIENTE C2 ON E1.CODMES = C2.CODMES AND E1.CODUNICOCLI = C2.CODUNICOCLI,
BDS.FRG_BASE_EXPOSICIONES E2,
DWHRIE.RCA_SALIDA_TIPO_BANCA C
WHERE E1.CODMES = &PERIODO_ACTUAL
AND E2.CODMES = &PERIODO_ANTERIOR
AND C.CODMES  = &PERIODO_ACTUAL
and e2.TIPCREDITO in ('06','07','08')
--AND C.CODBANCA IN ( 2,3)
AND E1.CODOPERACION = E2.CODOPERACION
AND E1.CODUNICOCLI = E2.CODUNICOCLI
AND E1.CODUNICOCLI = C.CODIGOUNICO
AND E1.TIPCREDITO in ('06','07','08')--'06'
AND E1.TIPCREDITO <> E2.TIPCREDITO
group by C.CODIGOUNICO, C2.APEPATERNO, E2.TIPCREDITO , E1.TIPCREDITO


--operaciones que migran de ponderador
SELECT  --e1.CODUNICOCLI,
--E1.CODOPERACION,
OP.PRODUCTOPCL, OP.SUBPRODUCTOPCL, E1.PCTPONDEXPOSICION, count(*),SUM(E1.mtoactmonsol) MONTO1, SUM(E2.mtoactmonsol) MONTO2, sum(e1.mtototalapr) apr1, sum(e2.mtototalapr) apr2
--, E2.*,
--E1.FECVENCIMIENTO FECVEN_FEBRERO, 
--E2.FECVENCIMIENTO FECVEN_MARZO,
--e2.mtoactmonsol MONTO
--SELECT COUNT(*)
FROM BDS.FRG_BASE_EXPOSICIONES E2,
BDS.FRG_BASE_EXPOSICIONES E1
left join BDS.BDR_MAEOPERACIONL OP ON E1.CODMES = OP.CODMES AND E1.CODUNICOCLI = OP.CODUNICOCLI 
                                AND E1.CODOPERACION = OP.CODOPERACION AND E1.CODMATRIZAPR = OP.CODMATRIZAPR
WHERE E2.CODMES = 201803
AND E2.TIPCREDITO = 12
AND E1.CODMES = 201802
AND E2.TIPCREDITO = E1.TIPCREDITO
AND E2.CODUNICOCLI = E1.CODUNICOCLI
AND E2.CODOPERACION = E1.CODOPERACION
AND E1.PCTPONDEXPOSICION >= 1.5
AND E2.PCTPONDEXPOSICION = 1
AND E2.MARCAPRODUCTO	= 'Tarjeta'
AND TO_CHAR(E2.FECVENCIMIENTO, 'YYYYMM') = 201804
AND TO_CHAR(E1.FECVENCIMIENTO, 'YYYYMM') > 202201
--AND e2.mtoactmonsol > 5000
group by OP.PRODUCTOPCL, OP.SUBPRODUCTOPCL, E1.PCTPONDEXPOSICION
